### ISSUE TITLE
does not compile (within ocrd_all, Ubuntu 18.04)

### ISSUE THREAD

**Issue by jbarth-ubhd** [OCR-D/ocrd_olena#29] opened 2020-02-13 13:58 UTC
```
jb@pers16:~/ocrd1804/ocrd_all> git log|head 
commit 0f7d5023992d19faa497096d445d88571fa1dbfe
Merge: 84bc669 f35fd3b
Author: Stefan Weil <sw@weilnetz.de>
Date:   Tue Feb 11 15:56:51 2020 +0100

    Merge pull request #61 from OCR-D/update-2020-02-11
    
    update 2020-02-11
```

```
jb@pers16:~/ocrd1804/ocrd_all/ocrd_olena> git log|head 
commit e0d8858fa24ca63bb1047045cc9ed05fdbb256fb
Merge: 55e8042 6e76bfe
Author: Konstantin Baierer <kba@users.noreply.github.com>
Date:   Thu Feb 6 14:56:43 2020 +0100

    Merge pull request #27 from stweil/work
    
    Add new macro BUILD_DIR for build directory

commit 6e76bfe3123996f4df0f13c3f2db1067dda280b0
```

`make all` within ~/ocrd1804/ocrd_all raises this error:

```
make[6]: Verzeichnis „/home/jb/ocrd1804/ocrd_all/venv/build/ocrd_olena/scribo/demo/xml2doc“ wird betreten
/usr/bin/moc -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ /home/jb/ocrd1804/ocrd_all/ocrd_olena/repo/olena/scribo/demo/xml2doc/common.hh -o common.moc.cc
Unknown options: isystem, isystem, isystem, isystem, isystem.
```

**Comment by stweil** [comment] 2020-02-14 12:50
Please try

    git -C /home/jb/ocrd1804/ocrd_all/ocrd_olena status
    git -C /home/jb/ocrd1804/ocrd_all/ocrd_olena/repo/olena status

Maybe the 2nd one is old. The current Makefile does not update it automatically, so you have to fix that manually (for example with `git submodule deinit ocrd_olena`).

**Comment by bertsky** [comment] 2020-03-06 18:48
@jbarth-ubhd can we close this?

**Comment by jbarth-ubhd** [comment] 2020-03-11 09:21
did `git -C ...`, `git -C ...` and `git submodule deinit ocrd_olena` 

Then `make all`

still does not work: 
```
Unknown options: isystem, isystem, isystem, isystem, isystem.
```

**Comment by stweil** [comment] 2020-03-11 18:18
My build does not enter `scribo/demo/xml2doc`. Yours should not, too. The olena build is [configured to not build the documentation](https://github.com/OCR-D/ocrd_olena/blob/master/Makefile#L91). That avoids the related build problem. For some unknown reason here make tries to build the documentation and fails of course. That has to be fixed.

I'd expect a subtile problem in the local installation. Does a fresh build starting with a new cloned OCR-D/ocrd_all work?

**Comment by jbarth-ubhd** [comment] 2020-03-12 08:27
```
rm -r ocrd_all
git clone ...
cd ocrd_all
sudo make deps-ubuntu
make all
...
...
make[6]: Verzeichnis „/home/jb/ocrd1804/ocrd_all/venv/build/ocrd_olena/scribo/demo/xml2doc“ wird betreten
/usr/bin/moc -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++  /home/jb/ocrd1804/ocrd_all/ocrd_olena/repo/olena/scribo/demo/xml2doc/common.hh -o common.moc.cc
Unknown options: isystem, isystem, isystem, isystem, isystem.
Makefile:1140: recipe for target 'common.moc.cc' failed
```

**Comment by stweil** [comment] 2020-03-18 20:55
Jochen, can you debug why the build enters that directory? Or perhaps reproduce the problem in a docker container, so that I can have a look on it?

**Comment by bertsky** [comment] 2020-03-18 21:15
> My build does not enter `scribo/demo/xml2doc`

@stweil are you sure about that? Mine does: it always builds `libexec/scribo/scribo-xml2doc` (which is then available as `scribo-cli xml2doc`).

> The olena build is [configured to not build the documentation](https://github.com/OCR-D/ocrd_olena/blob/master/Makefile#L91).

This is not about _documentation_, but _document_: to convert from the internal XML representation to PDF, HTML, SVG etc.

@jbarth-ubhd the above error message looks helpful, I will take a look.

Sorry, I should have looked at this more closely earlier!

**Comment by stweil** [comment] 2020-03-18 21:18
@bertsky, I did `grep` on a build protocol. I'll check once more, but not today.

**Comment by bertsky** [comment] 2020-03-18 21:55
Looks like your configure chose the wrong QT version. It should look for qt4, but found qt5 on your system. And `pkg-config` or `qtconfig` (or whatever) then returned a form of CFLAGS (GCC option  `-isystem`) that the moc code generator cannot parse.

Also, just in passing, if this `demo` binary requires QT, then we are missing `libqt4-dev` in `deps-ubuntu`. (So either we add that, or we find a way to disable building this part.)

@jbarth-ubhd can you please try the following:

1. install said package with apt-get and try:
   ```sh
   make -C ocrd_olena clean install
   ```
2. If that still does not help, try again with:
   ```sh
   make -C ocrd_olena clean install QT_PATH=/usr/bin QMAKE=/usr/bin/qmake
   ```

**Comment by bertsky** [comment] 2020-03-19 11:26
> @jbarth-ubhd can you please try the following:
> 
>     1. install said package with apt-get and try:
>        ```shell
>        make -C ocrd_olena clean install
>        ```
> 
>     2. If that still does not help, try again with:
>        ```shell
>        make -C ocrd_olena clean install QT_PATH=/usr/bin QMAKE=/usr/bin/qmake
>        ```

Scratch that: I have found a better way (`with-qt=no`). Can you please try with #45?

A recipe for that:

    git -C ocrd_olena fetch origin pull/45/head:pr-45
    git -C ocrd_olena checkout pr-45
    make -C ocrd_olena clean install

**Comment by stweil** [comment] 2020-03-19 11:53
> My build does not enter scribo/demo/xml2doc

There was no QT installed on the computer where I made the test, so that could explain why that part was not built for me. That is similar to @bertsky's solution which disabled the QT part of the build, no matter whether it is available or not.

**Closed as completed** 2020-03-19 13:17 UTC

**Comment by bertsky** [comment] 2020-03-19 13:19
This was closed automatically because of my PR description. @jbarth-ubhd If the problem persists with current master, please re-open!

**Comment by stweil** [comment] 2020-03-19 13:31
I updated OCR-D/ocrd_all now with latest ocrd_olena, so new builds should work.
